"""Ajout du champ priorite sur Tache

Revision ID: 0c9b0f2d60cf
Revises: 7193f785fb6f
Create Date: 2025-12-09 20:01:46.486644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c9b0f2d60cf'
down_revision = '7193f785fb6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priorite', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taches', schema=None) as batch_op:
        batch_op.drop_column('priorite')

    # ### end Alembic commands ###
