"""auto increment task id

Revision ID: 7193f785fb6f
Revises: 
Create Date: 2025-12-02 20:28:27.159311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7193f785fb6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groupes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('liste_taches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('groupe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['groupe_id'], ['groupes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_groups',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('groupe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['groupe_id'], ['groupes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'groupe_id')
    )
    op.create_table('taches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('libelle', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('etat', sa.Enum('EN_COURS', 'TERMINEE', 'ARCHIVEE', name='etat'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('liste_tache_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['liste_tache_id'], ['liste_taches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taches')
    op.drop_table('users_groups')
    op.drop_table('liste_taches')
    op.drop_table('users')
    op.drop_table('groupes')
    # ### end Alembic commands ###
